# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGES',
            fields=[
                ('IMAGES_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMAGES_URL', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='LOST',
            fields=[
                ('LOST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LOST_TIME', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('POST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('POST_TITLE', models.CharField(max_length=128)),
                ('POST_TEXT', models.TextField()),
                ('POST_LOCAL', models.CharField(max_length=128)),
                ('POST_TIME', models.DateTimeField()),
                ('POST_BASE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.POST')),
                ('POST_IMAGES', models.ManyToManyField(null=True, to='core.IMAGES')),
            ],
        ),
        migrations.CreateModel(
            name='TAGS',
            fields=[
                ('TAG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TAG_NAME', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=32)),
                ('USER_PASSWORD', models.CharField(max_length=255)),
                ('USER_FULLNAME', models.CharField(max_length=128)),
                ('USER_BIRTHDAY', models.DateField()),
                ('USER_EMAIL', models.EmailField(max_length=128)),
                ('USER_TELEPHONE', models.CharField(max_length=32)),
                ('USER_MATRICULA', models.CharField(max_length=16)),
                ('USER_DESCRIPTION', models.CharField(max_length=255)),
                ('USER_CAMPUS', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='POST_TAGS',
            field=models.ManyToManyField(to='core.TAGS'),
        ),
        migrations.AddField(
            model_name='post',
            name='POST_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.USER'),
        ),
        migrations.AddField(
            model_name='lost',
            name='LOST_POST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.POST'),
        ),
        migrations.AddField(
            model_name='lost',
            name='LOST_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.USER'),
        ),
    ]
