# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190515_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='POST_IMAGES',
            field=models.ManyToManyField(blank=True, to='core.IMAGE'),
        ),
    ]
