# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190515_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_CAMPUS',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_EMAIL',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_NAME',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
