# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190515_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='POST_TAGS',
        ),
        migrations.AlterField(
            model_name='post',
            name='POST_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
