# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190521_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='POST_BASE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='POST_IMAGES',
        ),
    ]
