# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190521_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='POST_USER',
            field=models.IntegerField(),
        ),
    ]
