# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190521_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='POST_USER',
        ),
    ]
