# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='POST_BASE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.POST'),
        ),
        migrations.AddField(
            model_name='post',
            name='POST_IMAGES',
            field=models.ManyToManyField(blank=True, to='core.IMAGE'),
        ),
        migrations.AddField(
            model_name='post',
            name='POST_USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.USER'),
            preserve_default=False,
        ),
    ]
